pipeline:
 - name: Install dependencies
   type: command
   command: composer install --no-interaction --optimize-autoloader
   directory: $APP_ROOT
 - name: Build site
   type: command
   command: drush si disaster_recovery --account-name=luke --account-mail=lukemartinwebdev@gmail.com --account-pass=nI0w!922m# --config-dir=/var/www/html/config/sync --root=/var/www/html/web -y
   directoy: /var/www/html/web
